### ISSUE TITLE
How to get API key

### ISSUE THREAD

**Issue by ghost** [gjordi/mapquest-open-geocoding#1]
Your example working absolutely fine for me when I'm sending any addresses using your key (Fmjtd|luur2hu1n5,2s=o5-9wawhy). However when I'm using my key (generated from Google Map API leys, https://developers.google.com/maps/documentation/javascript/tutorial) it not working and giving 403 Forbidden error. Can you help?

**Comment by gjordi** [comment]
You will need to create a mapquest developer account and register for a key here:

  http://developer.mapquest.com/web/products/open

**Comment by ghost** [comment]
Right, I already tried that. It will not allow you to create free key as well as Paid key? For now I am only trying to get free key. Could you please try that to create yourself once ? Please guide me

**Comment by gjordi** [comment]
It appears MapQuest has recently updated their web site and are now offering a variety of plans.  You can signup for the 'Free Trial' plan here:

https://developer.mapquest.com

**Comment by pashtika** [comment]
Thank you. Could you please let know why following MapQuest's nominatim not working
http://open.mapquestapi.com/nominatim/v1/search.php?format=json&q=12 Queen Street STE 2 WORCESTER MA 16102411

Please guide ASAP

**Comment by gjordi** [comment]
Nominatim is a service written by the folks at openstreetmap.  The documentation, http://wiki.openstreetmap.org/wiki/Nominatim does a very good job of explaining how to use it.
